[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#ffe81f"  # Gelb – wie der Star Wars Text "A long time ago..."
backgroundColor = "#000000"  # Schwarz – tiefer Weltraum
secondaryBackgroundColor = "#1c1c1c"  # Dunkelgrau – z. B. Raumschiff-Elemente
textColor = "#ffffff"  # Weiß – starke Lesbarkeit im Dunkeln
font = "monospace"